packages:
  - apps/*
  - packages/*
catalog:
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@eslint-react/eslint-plugin': ^1.52.2
  '@phaicom/eslint-config': ^0.3.1
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react-swc': ^3.10.2
  eslint: ^9.29.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  globals: ^16.2.0
  lint-staged: ^16.1.2
  react: ^19.1.0
  react-dom: ^19.1.0
  simple-git-hooks: ^2.13.0
  turbo: ^2.5.4
  typescript: ~5.8.3
  vite: ^6.3.5
