packages:
  - apps/*
  - packages/*
catalog:
  "@commitlint/cli": ^19.8.1
  "@commitlint/config-conventional": ^19.8.1
  "@eslint-react/eslint-plugin": ^1.52.2
  "@hookform/resolvers": ^5.1.1
  "@phaicom/eslint-config": ^0.3.1
  "@radix-ui/react-accordion": ^1.2.11
  "@radix-ui/react-checkbox": ^1.3.2
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-select": ^2.2.5
  "@radix-ui/react-slot": ^1.2.3
  "@tailwindcss/vite": ^4.1.11
  "@types/node": ^24.0.4
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@vitejs/plugin-react-swc": ^3.10.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  embla-carousel-react: ^8.6.0
  eslint: ^9.29.0
  eslint-plugin-better-tailwindcss: ^3.4.2
  eslint-plugin-format: ^1.0.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  globals: ^16.2.0
  libphonenumber-js: ^1.12.9
  lint-staged: ^16.1.2
  lucide-react: ^0.523.0
  next-themes: ^0.4.6
  react: ^19.1.0
  react-dom: ^19.1.0
  react-hook-form: ^7.58.1
  simple-git-hooks: ^2.13.0
  sonner: ^2.0.5
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  turbo: ^2.5.4
  tw-animate-css: ^1.3.4
  typescript: ~5.8.3
  vite: ^6.3.5
  zod: ^3.25.67
